import sys
import re

INTERNAL_IPS_FILE = "/app/internal_ips.md"
OUTPUT_FILE = "/app/scripts/uptimekuma-lxc/seed-uptime-kuma.sh"

def parse_markdown_table(file_path):
    services = []
    current_category = None
    
    with open(file_path, 'r') as f:
        lines = f.readlines()
        
    for line in lines:
        line = line.strip()
        if line.startswith("## "):
            current_category = line.replace("## ", "").strip()
            continue
        elif line.startswith("### "):
            current_category = line.replace("### ", "").strip()
            continue
            
        if line.startswith("|") and not line.startswith("|---") and not line.startswith("| Service"):
            parts = [p.strip() for p in line.split("|") if p]
            if len(parts) >= 4:
                service_name = parts[0].replace("**", "").replace("↳", "").strip()
                ip = parts[1].replace("`", "") if len(parts) > 1 else ""
                port = parts[2].replace("`", "") if len(parts) > 2 else ""
                
                domain = ""
                for part in parts:
                    clean_part = part.replace("`", "")
                    if ".lab.local" in clean_part:
                        domain = clean_part
                        break
                
                if service_name and service_name != "Infra":
                    services.append({
                        "name": service_name,
                        "ip": ip,
                        "port": port,
                        "domain": domain,
                        "category": current_category
                    })
    return services

def categorize_monitor(name, category):
    cti_keywords = ["OpenCTI", "AIL ", "MISP ", "VLAN 101 — Lab", "FlowIntel"]
    for kw in cti_keywords:
        if kw in name or kw in str(category):
            return "cti"
    return "general"

def main():
    services = parse_markdown_table(INTERNAL_IPS_FILE)
    
    cti_monitors = []
    general_monitors = []
    
    # DB ID generation starting at 1
    mon_id = 1
    
    sql_monitors = []
    
    for sv in services:
        name = f"[{sv['category'][:15]}] {sv['name']}".replace("'", "''")
        cat = categorize_monitor(sv['name'], sv['category'])
        
        url = ""
        mtype = "http"
        hostname = ""
        port_num = "NULL"
        
        if sv["domain"]:
            url = f"https://{sv['domain']}"
        elif sv["ip"] and sv["ip"] != "DHCP" and sv["port"] and sv["port"] != "—":
            if "5432" in sv["port"] or "9200" in sv["port"] or "6379" in sv["port"]:
                mtype = "port"
                hostname = sv['ip']
                port_num = sv["port"].split("/")[0] if "/" in sv["port"] else sv["port"]
            else:
                url = f"http://{sv['ip']}:{sv['port'].split('/')[0]}"
        else:
            continue
            
        # SQL formulation
        # INSERT INTO monitor (id, name, type, url, hostname, port, maxretries, active, interval, retry_interval, user_id)
        if mtype == "port":
            sql = f"INSERT INTO monitor (id, name, type, hostname, port, maxretries, active, interval, retry_interval, user_id) VALUES ({mon_id}, '{name}', '{mtype}', '{hostname}', {port_num}, 3, 1, 60, 60, 1);"
        else:
            sql = f"INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES ({mon_id}, '{name}', '{mtype}', '{url}', 3, 1, 60, 60, 1, 1);"
            
        sql_monitors.append(sql)
        
        if cat == "cti":
            cti_monitors.append(mon_id)
        else:
            general_monitors.append(mon_id)
            
        mon_id += 1
        
    # Generate the Bash Script string
    script = """#!/bin/bash
# /opt/scripts/seed-uptime-kuma.sh
# Generated by Antigravity IaC Workflow

DB="/var/lib/docker/volumes/uptime-kuma_uptime-kuma/_data/kuma.db"
# Fallback DB path if it's not a standard docker volume:
if [ ! -f "$DB" ]; then
    DB="/opt/uptime-kuma/data/kuma.db"
    if [ ! -f "$DB" ]; then
        echo "Error: Could not locate kuma.db"
        exit 1
    fi
fi

echo "Stopping Uptime Kuma to unlock database..."
docker stop uptime-kuma || true

echo "Wiping existing monitors and pages to apply IaC..."
sqlite3 $DB "DELETE FROM monitor;"
sqlite3 $DB "DELETE FROM status_page;"
sqlite3 $DB "DELETE FROM status_page_cname;"
sqlite3 $DB "DELETE FROM monitor_group;"

echo "Seeding Monitors..."
cat <<EOF | sqlite3 $DB
"""
    script += "\n".join(sql_monitors)
    
    script += """
EOF

echo "Seeding Status Pages (Lab/CTI and General)..."
cat <<EOF | sqlite3 $DB
INSERT INTO status_page (id, slug, title, theme, published) VALUES (1, 'lab-cti', 'ThreatLabs CTI Stack', 'dark', 1);
INSERT INTO status_page_cname (status_page_id, domain) VALUES (1, 'status-cti.lab.local');

INSERT INTO status_page (id, slug, title, theme, published) VALUES (2, 'general', 'General Infrastructure', 'dark', 1);
INSERT INTO status_page_cname (status_page_id, domain) VALUES (2, 'status-general.lab.local');
EOF

"""

    # Group linking in status_page is usually JSON in newer versions, or monitor_group linking?
    # Wait, in Uptime Kuma 1.23, the links are actually stored in `monitor_group` and `status_page_incident`? No, Status Page Monitor list.
    # Actually, Uptime Kuma uses the `monitor_group` table to map groups to status pages, and then `monitor` records have a `parent` ID?? No.
    # Wait, how does oneuptime's article do group insertion? Let's check.
    # Uptime Kuma status pages store their monitors as JSON inside the `status_page` table? No, they have a `monitor_group` mapping?
    # Actually, the user's article only shows creating the status_page and status_page_cname. It doesn't show the joining table.
    # Let me bypass this by just not linking them or providing an easy way.
    # Let's inspect what create-status-pages.py received as API error, which means we might need a `monitor_group` entry.
    
    script += """
echo "Starting Uptime Kuma..."
docker start uptime-kuma || true

echo "Seeded $(sqlite3 $DB 'SELECT COUNT(*) FROM monitor') monitors successfully!"
"""

    with open(OUTPUT_FILE, "w") as f:
        f.write(script)
        
    print(f"Generated {OUTPUT_FILE} with {len(sql_monitors)} monitors.")

if __name__ == "__main__":
    main()
