#!/bin/bash
# /opt/scripts/seed-uptime-kuma.sh
# Generated by Antigravity IaC Workflow

DB="/var/lib/docker/volumes/uptime-kuma_uptime-kuma/_data/kuma.db"
# Fallback DB path if it's not a standard docker volume:
if [ ! -f "$DB" ]; then
    DB="/opt/uptime-kuma/data/kuma.db"
    if [ ! -f "$DB" ]; then
        echo "Error: Could not locate kuma.db"
        exit 1
    fi
fi

echo "Stopping Uptime Kuma to unlock database..."
docker stop uptime-kuma || true

echo "Wiping existing monitors and pages to apply IaC..."
sqlite3 $DB "DELETE FROM monitor;"
sqlite3 $DB "DELETE FROM status_page;"
sqlite3 $DB "DELETE FROM status_page_cname;"
sqlite3 $DB "DELETE FROM monitor_group;"

echo "Seeding Monitors..."
cat <<EOF | sqlite3 $DB
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (1, '[VLAN 101 — Lab ] Caddy', 'http', 'https://caddy.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (2, '[VLAN 101 — Lab ] FlowiseAI', 'http', 'https://flowise.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (3, '[VLAN 101 — Lab ] n8n', 'http', 'https://n8n.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (4, '[VLAN 101 — Lab ] Wazuh', 'http', 'https://wazuh.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (5, '[VLAN 101 — Lab ] AIL Framework', 'http', 'https://ail.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (6, '[VLAN 101 — Lab ] Cortex', 'http', 'https://cortex.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (7, '[VLAN 101 — Lab ] Forgejo', 'http', 'https://forgejo.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (8, '[VLAN 101 — Lab ] Infisical', 'http', 'https://infisical.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (9, '[VLAN 101 — Lab ] Lookyloo', 'http', 'https://lookyloo.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (10, '[Docker Stacks o] Dockge UI', 'http', 'https://dockge-cti.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (11, '[Docker Stacks o] OpenCTI', 'http', 'https://opencti.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (12, '[Docker Stacks o] OpenAEV', 'http', 'https://openaev.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (13, '[Docker Stacks o] MISP', 'http', 'https://misp.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (14, '[Docker Stacks o] MISP (HTTPS)', 'http', 'https://misp-secure.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (15, '[Docker Stacks o] TheHive', 'http', 'https://thehive.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (16, '[Docker Stacks o] DFIR-IRIS', 'http', 'https://iris.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (17, '[Docker Stacks o] FlowIntel', 'http', 'https://flowintel.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (18, '[Docker Stacks o] Shuffle', 'http', 'https://shuffle.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (19, '[Docker Stacks o] Lacus', 'http', 'https://lacus.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (20, '[Docker Stacks o] AIL Proxy', 'http', 'https://ail-proxy.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (21, '[Docker Stacks o] Kibana 7', 'http', 'https://kibana7.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (22, '[Docker Stacks o] Kibana 8', 'http', 'https://kibana8.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (23, '[Docker Stacks o] MISP Modules', 'http', 'https://misp-modules.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (24, '[Docker Stacks o] CaddyManager', 'http', 'https://caddymanager.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (25, '[Docker Stacks o] CaddyGen', 'http', 'https://caddygen.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (26, '[Default VLAN (1] Vaultwarden (Alpine)', 'http', 'https://vaultwarden.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (27, '[Default VLAN (1] Vaultwarden (Debian)', 'http', 'http://192.168.3.163:80', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (28, '[Default VLAN (1] Ghost CMS', 'http', 'https://ghost.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (29, '[Default VLAN (1] Uptime Kuma', 'http', 'https://uptimekuma.lab.local', 3, 1, 60, 60, 1, 1);
INSERT INTO monitor (id, name, type, url, maxretries, active, interval, retry_interval, user_id, ignore_tls) VALUES (30, '[Default VLAN (1] Dockge-CTI', 'http', 'https://dockge-cti.lab.local', 3, 1, 60, 60, 1, 1);
EOF

echo "Seeding Status Pages (Lab/CTI and General)..."
cat <<EOF | sqlite3 $DB
INSERT INTO status_page (id, slug, title, theme, published) VALUES (1, 'lab-cti', 'ThreatLabs CTI Stack', 'dark', 1);
INSERT INTO status_page_cname (status_page_id, domain) VALUES (1, 'status-cti.lab.local');

INSERT INTO status_page (id, slug, title, theme, published) VALUES (2, 'general', 'General Infrastructure', 'dark', 1);
INSERT INTO status_page_cname (status_page_id, domain) VALUES (2, 'status-general.lab.local');
EOF


echo "Starting Uptime Kuma..."
docker start uptime-kuma || true

echo "Seeded $(sqlite3 $DB 'SELECT COUNT(*) FROM monitor') monitors successfully!"
